FROM ubuntu:20.04
RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker
RUN DEBIAN_FRONTEND=noninteractive \
  apt-get update \
  && apt-get install -y python3 \
  && apt-get install -y curl \
  && apt-get -y install python3-pip \
  && rm -rf /var/lib/apt/lists/*


RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir urllib3 requests

WORKDIR /home/web

COPY flutter_web_app/build/web .
COPY backend/backend_v001.py .

CMD [ "python3", "./backend_v001.py"]

